core/urls.py
from django.urls import path
from core import views
from django.conf.urls.static import static
from django.conf import settings


app_name = "core"

urlpatterns = [
    path("", views.index, name="index"),

    path("user/insert/", views.user_insert, name="user_insert"),
    path("user/select/", views.user_select, name="user_select"),
    path("user/<int:user_id>/", views.get_user_by_id, name="get_user_by_id"),

    path("chapter/insert/", views.chapter_insert, name="chapter_insert"),
    path("chapter/select/", views.chapter_select, name="chapter_select"),
    path("chapter/<int:chapter_id>/", views.get_chapter_by_id, name="get_chapter_by_id"),

    path("book/insert/", views.book_insert, name="book_insert"),
    path("book/select/", views.book_select, name="book_select"),
    path("book/<int:book_id>/", views.get_book_by_id, name="get_book_by_id"),
    path("book/genre/<str:slug>/", views.get_books_by_genre, name="get_books_by_genre"),
    path("book/tag/<str:slug>/", views.get_books_by_tag, name="get_books_by_tag"),

    path("tag/insert/", views.tag_insert, name="tag_insert"),
    path("tag/select/", views.tag_select, name="tag_select"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sqlcrutch/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls"))
]

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from .utils import slugify
from django.conf import settings


class Book(models.Model):
    title = models.CharField(max_length=50, unique=True)
    description = models.TextField()
    views = models.PositiveIntegerField(default=0)
    pub_date = models.DateTimeField(default=timezone.now)
    image = models.ImageField(upload_to=settings.IMAGE_FOLDER)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="books")
    tags = models.ManyToManyField("Tag", blank=True, related_name="books")
    genres = models.ManyToManyField("Genre", blank=True, related_name="books")

    def __str__(self):
        return self.title


class Chapter(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name="chapters")
    num = models.FloatField()
    title = models.CharField(max_length=50)
    text = models.TextField()
    pub_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.book.title}:{self.title}"


class Tag(models.Model):    
    title = models.CharField(max_length=60)     
    slug = models.SlugField(blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'


class Genre(models.Model):    
    title = models.CharField(max_length=60)     
    slug = models.SlugField(blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'

core/forms.py
from django import forms
from .models import Book, Tag, Chapter
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class BookForm(forms.ModelForm):
	class Meta:
		model = Book
		fields = ['title', 'description', 'image', 'tags', 'genres', "author"]


class RegForm(UserCreationForm):
	email = forms.EmailField(max_length=254, help_text='')
	username = forms.CharField(max_length = 100, help_text='')
	password1 = forms.CharField(max_length = 100, help_text='')
	password2 = forms.CharField(max_length = 100, help_text='')
	first_name = forms.CharField(max_length = 100, help_text='')

	class Meta:
		model = User
		fields = ['username', 'email', 'first_name', 'password1', 'password2', ]


class ChapterForm(forms.ModelForm):
	class Meta:
		model = Chapter
		fields = ["book", "num", "title", "text"]

core/views.py
from django.shortcuts import render, redirect
from .forms import BookForm, RegForm, ChapterForm
from django.views.decorators.csrf import csrf_exempt
from django.db import connections
from django.contrib.auth.hashers import make_password
from .utils import slugify, get_tags, get_genres, generate, image_save, get_users, get_books, get_chapters
from django.conf import settings

def index(request):
    return render(request, "core/base.html")


@csrf_exempt
def user_insert(request):
    if request.method == "POST":
        if request.POST.get("password2") != request.POST.get("password1"):
            raise Exception("Password fields are not equal")
        with connections.create_connection("default").cursor() as cursor:
            cursor.execute("""
                INSERT INTO auth_user (is_superuser, is_staff, is_active, date_joined, username, email, first_name, password, last_name)
                VALUES (false, false, false, CURRENT_TIMESTAMP, %s, %s, %s, %s, %s)
            """, [request.POST.get("username"), request.POST.get("email"), request.POST.get("first_name"), make_password(request.POST.get("password2")), request.POST.get("last_name")])
    return render(request, "core/user_insert.html", {"form": RegForm()})


def user_select(request):
    users = get_users()
    return render(request, "core/user_select.html", {"users": users})


@csrf_exempt
def chapter_insert(request):
    books = get_books()
    if request.method == "POST":
        with connections.create_connection("default").cursor() as cursor:
            if not request.POST.get("num"):
                num = 0
            else:
                num = request.POST.get("num")
            cursor.execute("""
                INSERT INTO core_chapter (title, num, text, pub_date, book_id)
                VALUES (%s, %s, %s, CURRENT_TIMESTAMP, %s)
            """, [request.POST.get("title"), num, request.POST.get("text"), request.POST.get("book")])
    return render(request, "core/chapter_insert.html", {"books": books})


def chapter_select(request):
    chapters = get_chapters()
    return render(request, "core/chapter_select.html", {"chapters": chapters})


@csrf_exempt
def book_insert(request):
    tags = get_tags()
    genres = get_genres()
    users = get_users()
    if request.method == "POST":
        image = image_save(request.FILES["image"])
        title = request.POST.get("title")
        description = request.POST.get("description")
        tag_ids = request.POST.getlist("tags")
        genre_ids = request.POST.getlist("genres")
        author_id = request.POST.get("author")
        with connections.create_connection("default").cursor() as cursor:
            cursor.execute("""
                INSERT INTO core_book (title, description, author_id, image, views, pub_date)
                VALUES (%s, %s, %s, %s, 0, CURRENT_TIMESTAMP)
            """, [title, description, author_id, image])
            cursor.execute("SELECT id FROM core_book WHERE title = %s", [title,])
            book_id = cursor.fetchone()[0]
            for genre_id in genre_ids:
                cursor.execute("""
                    INSERT INTO core_book_genres (book_id, genre_id)
                    VALUES (%s, %s)
                """, [book_id, genre_id])
            for tag_id in tag_ids:
                cursor.execute("""
                    INSERT INTO core_book_tags (book_id, tag_id)
                    VALUES (%s, %s)
                """, [book_id, tag_id])
    return render(request, "core/book_insert.html", {"genres": genres, "tags": tags, "users": users})


def book_select(request):
    books = get_books()
    return render(request, "core/book_select.html", {"books": books})


@csrf_exempt
def tag_insert(request):
    if request.method == "POST":
        with connections.create_connection("default").cursor() as cursor:
            if not request.POST.get("slug"):
                slug = slugify(request.POST.get("title"))
            else:
                slug = request.POST.get("slug")
            cursor.execute("""
                INSERT INTO core_tag (title, slug)
                VALUES (%s, %s)
            """, [request.POST.get("title").lower(), slug])
    return render(request, "core/tag_insert.html")


def tag_select(request):
    tags = get_tags()
    return render(request, "core/tag_select.html", {"tags": tags})


def get_books_by_genre(request, slug):
    data = get_books()
    books = []
    for book in data:
        for genre in book["genres"]:
            if genre["slug"] == slug:
                books.append(book)
                break
    return render(request, "core/book_select.html", {"books": books})


def get_books_by_tag(request, slug):
    data = get_books()
    books = []
    for book in data:
        for tag in book["tags"]:
            if tag["slug"] == slug:
                books.append(book)
                break
    return render(request, "core/book_select.html", {"books": books})


def get_book_by_id(request, book_id):
    books = get_books(f"WHERE core_book.id={book_id}")
    return render(request, "core/book_select.html", {"books": books})


def get_chapter_by_id(request, chapter_id):
    chapters = get_chapters(f"WHERE id={chapter_id}")
    return render(request, "core/chapter_select.html", {"chapters": chapters})


def get_user_by_id(request, user_id):
    users = get_users(f"WHERE id = {user_id}")
    return render(request, "core/user_select.html", {"users": users})

templates/core/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>select</title>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>

{% include 'core/header.html' %}

{% block main_content %}{% endblock %}

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

templates/core/book_insert.html
{% extends 'core/base.html' %}

{% block main_content %}{% spaceless %}
<form method="post" enctype="multipart/form-data">
  <p>
    <label for="id_title">Title:</label>
    <input type="text" name="title" maxlength="50" required="" id="id_title">
  </p>
  <p>
    <label for="id_description">Description:</label>
    <textarea name="description" cols="40" rows="10" required="" id="id_description"></textarea>
  </p>
  <p>
    <label for="id_image">Image:</label>
    <input type="file" name="image" accept="image/*" required="" id="id_image">
  </p>
  <p>
    <label for="id_tags">Tags:</label>
    <select name="tags" id="id_tags" multiple="">
  {% for tag in tags %}
  <option value="{{tag.id}}">{{tag.title}}</option>
  {% endfor %}
</select>
  </p>
  <p>
    <label for="id_genres">Genres:</label>
    <select name="genres" id="id_genres" multiple="">
  {% for genre in genres %}
  <option value="{{genre.id}}">{{genre.title}}</option>
  {% endfor %}
</select>
  </p>
  <p>
    <label for="id_author">Author:</label>
    <select name="author" required="" id="id_author">
      <option value="" selected="">---------</option>
      {% for user in users %}
      <option value="{{user.id}}">{{user.username}}</option>
      {% endfor %}
    </select>
  </p>
  <input type="submit" value="Send">

</form>
{% endspaceless %}{% endblock %}

templates/core/book_select.html
{% extends 'core/base.html' %}

{% block main_content %}{% spaceless %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col">title</th>
      <th scope="col">description</th>
      <th scope="col">views</th>
      <th scope="col">pub_date</th>
      <th scope="col">author_id</th>
      <th scope="col">image</th>
      <th scope="col">genres</th>
      <th scope="col">tags</th>
    </tr>
  </thead>
  <tbody>
  	{% for book in books %}
    <tr>
      <th scope="row">{{book.id}}</th>
      <td>{{book.title}}</td>
      <td>{{book.description}}</td>
      <td>{{book.views}}</td>
      <td>{{book.pub_date}}</td>
      <td><a href="{% url 'core:get_user_by_id' book.author_id %}">{{book.author_username}}</a></td>
      <td><img src="{{book.image}}" height="40px"></td>
      <td>
        {% for genre in book.genres %}
        <p><a href="{% url 'core:get_books_by_genre' genre.slug %}">{{genre.title}}</a></p>
        {% endfor %}
      </td>
      <td>
        {% for tag in book.tags %}
        <p><a href="{% url 'core:get_books_by_tag' tag.slug %}">{{tag.title}}</a></p>
        {% endfor %}
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endspaceless %}{% endblock %}

templates/core/chapter_insert.html
{% extends 'core/base.html' %}

{% block main_content %}{% spaceless %}
<form method="post">
	<p>
		<label for="id_book">Book:</label>
		<select name="book" required="" id="id_book">
			<option value="" selected="">---------</option>
			{% for book in books %}
			<option value="{{book.id}}">{{book.title}}</option>
			{% endfor %}
		</select>
	</p>
	<p>
		<label for="id_num">Num:</label>
		<input type="number" name="num" step="any" required="" id="id_num">
	</p>
	<p>
		<label for="id_title">Title:</label>
		<input type="text" name="title" maxlength="50" required="" id="id_title">
	</p>
	<p>
		<label for="id_text">Text:</label>
		<textarea name="text" cols="40" rows="10" required="" id="id_text"></textarea>
	</p>
	<input type="submit" value="Send">
</form>
{% endspaceless %}{% endblock %}

templates/core/chapter_select.html
{% extends 'core/base.html' %}

{% block main_content %}{% spaceless %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col">num</th>
      <th scope="col">title</th>
      <th scope="col">text</th>
      <th scope="col">pub_date</th>
      <th scope="col">book_id</th>
    </tr>
  </thead>
  <tbody>
  	{% for chapter in chapters %}
    <tr>
      <th scope="row">{{chapter.id}}</th>
      <td>{{chapter.num}}</td>
      <td>{{chapter.title}}</td>
      <td>{{chapter.text}}</td>
      <td>{{chapter.pub_date}}</td>
      <td>{{chapter.book_id}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endspaceless %}{% endblock %}

templates/core/header.html
<header style="height: 90px; width: 100%; background: grey;">
	<nav style="display: inline-block; text-align: center; width: 100%;">
		<a class="nav_link" href="{% url 'core:user_select' %}">user select</a>
		<a class="nav_link" href="{% url 'core:user_insert' %}">user insert</a>
		<a class="nav_link" href="{% url 'core:book_select' %}">book select</a>
		<a class="nav_link" href="{% url 'core:book_insert' %}">book insert</a>
		<a class="nav_link" href="{% url 'core:tag_select' %}">tag select</a>
		<a class="nav_link" href="{% url 'core:tag_insert' %}">tag insert</a>
		<a class="nav_link" href="{% url 'core:chapter_select' %}">chapter select</a>
		<a class="nav_link" href="{% url 'core:chapter_insert' %}">chapter insert</a>
	</nav>
</header>
<style type="text/css">
	
.nav_link{
	color: white;
	text-decoration: none;
	border: 1px solid black;
	padding: 10px;
	margin: 0px 20px;
}
.nav_link:hover{
	color: black;
}

header{
	padding-top: 30px;
}

</style>

templates/core/index.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>test</title>
</head>
<body>

</body>
</html>

templates/core/tag_insert.html
{% extends 'core/base.html' %}

{% block main_content %}{% spaceless %}


<form method="post">
	<p>
    <label for="tag_title">Title:</label>
	<input type="text" name="title" id="tag_title">
	</p>
	<p>
    <label for="tag_slug">Slug:</label>
	<input type="text" name="slug" id="tag_slug">
	</p>
	<p>
	<input type="submit" value="Send">
	</p>
</form>

{% endspaceless %}{% endblock %}

templates/core/tag_select.html
{% extends 'core/base.html' %}

{% block main_content %}{% spaceless %}

<table class="table">
  <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col">title</th>
      <th scope="col">slug</th>
    </tr>
  </thead>
  <tbody>
  	{% for tag in tags %}
    <tr>
      <th scope="row">{{tag.id}}</th>
      <td>{{tag.title}}</td>
      <td>{{tag.slug}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endspaceless %}{% endblock %}

templates/core/user_insert.html
{% extends 'core/base.html' %}

{% block main_content %}{% spaceless %}

<form method="post">

<p>
    <label for="id_username">Username:</label>
    <input type="text" name="username" maxlength="100" autofocus="" required="" id="id_username">
  </p>
  <p>
    <label for="id_email">Email:</label>
    <input type="email" name="email" maxlength="254" required="" id="id_email">
  </p>
  <p>
    <label for="id_first_name">First name:</label>
    <input type="text" name="first_name" maxlength="100" required="" id="id_first_name">
  </p>
  <p>
    <label for="id_first_name">Last name:</label>
    <input type="text" name="last_name" maxlength="100" required="" id="id_last_name">
  </p>
  <p>
    <label for="id_password1">Password1:</label>
    <input type="text" name="password1" maxlength="100" required="" id="id_password1">
  </p>
  <p>
    <label for="id_password2">Password2:</label>
    <input type="text" name="password2" maxlength="100" required="" id="id_password2">
  </p>
  <input type="submit" value="Send">
</form>
</body>
</html>
{% endspaceless %}{% endblock %}

templates/core/user_select.html
{% extends 'core/base.html' %}

{% block main_content %}{% spaceless %}

<table class="table">
  <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col">username</th>
      <th scope="col">email</th>
      <th scope="col">first_name</th>
      <th scope="col">last_name</th>
    </tr>
  </thead>
  <tbody>
  	{% for user in users %}
    <tr>
      <th scope="row"><a href="{% url 'core:get_user_by_id' user.id %}">{{user.id}}</a></th>
      <td>{{user.username}}</td>
      <td>{{user.email}}</td>
      <td>{{user.first_name}}</td>
      <td>{{user.last_name}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endspaceless %}{% endblock %}